"""
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

USE_TZ = True
USE_I18N = True
TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'en-us'

]
    },
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    {
    },
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    {
    },
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    {
    },
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    {
AUTH_PASSWORD_VALIDATORS = [

}
    }
        'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.sqlite3',
    'default': {
DATABASES = {

WSGI_APPLICATION = 'backend.wsgi.application'

]
    },
        },
            ],
                'django.contrib.messages.context_processors.messages',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.request',
            'context_processors': [
        'OPTIONS': {
        'APP_DIRS': True,
        'DIRS': [BASE_DIR / 'backend' / 'templates'],
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    {
TEMPLATES = [

ROOT_URLCONF = 'backend.urls'

]
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
MIDDLEWARE = [

]
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
INSTALLED_APPS = [
# Application definition

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '.onrender.com').split(',')

DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
# SECURITY WARNING: don't run with debug turned on in production!

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'unsafe-default')
# SECURITY WARNING: keep the secret key used in production secret!

# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# Quick-start development settings - unsuitable for production

BASE_DIR = Path(__file__).resolve().parent.parent
# Build paths inside the project like this: BASE_DIR / 'subdir'.

from pathlib import Path
import os

"""
https://docs.djangoproject.com/en/5.2/ref/settings/
For the full list of settings and their values, see

https://docs.djangoproject.com/en/5.2/topics/settings/
For more information on this file, see

Generated by 'django-admin startproject' using Django 5.2.9.

Django settings for backend project.

